
DROP DATABASE IF EXISTS examdb;


DROP ROLE IF EXISTS examdb;


CREATE ROLE examdb LOGIN PASSWORD 'pass'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;


CREATE DATABASE examdb WITH OWNER = examdb ENCODING = 'UTF8';
